In [112]:
a=10
b=10.0

In [113]:
a

10

In [114]:
b

10.0

In [115]:
10+20-30*2

-30

In [116]:
str="Hello Welcome"

In [117]:
str

'Hello Welcome'

In [118]:
s='Hello'
s

'Hello'

In [119]:
s[0]

'H'

In [120]:
len(str)

13

In [121]:
s[-1]

'o'

In [122]:
len(s)

5

In [123]:
str[0:5]

'Hello'

In [124]:
str[:6]

'Hello '

In [125]:
str[-7:-1]

'Welcom'

str[-7:0]

In [126]:
str[-7:0]

''

In [127]:
str[-7::]

'Welcome'

In [128]:
str[::-9]

'el'

In [129]:
str[-13:-10]

'Hel'

In [130]:
str="Hello Welcome you all"
str

'Hello Welcome you all'

In [131]:
print(str)

Hello Welcome you all


In [132]:
str*10

'Hello Welcome you allHello Welcome you allHello Welcome you allHello Welcome you allHello Welcome you allHello Welcome you allHello Welcome you allHello Welcome you allHello Welcome you allHello Welcome you all'

In [133]:
len(str)

21

In [134]:
str.find("Hel")

0

In [135]:
str.find("yo")

14

In [136]:
str.find("cse")

-1

In [137]:
str.upper()

'HELLO WELCOME YOU ALL'

In [138]:
str.lower()

'hello welcome you all'

In [139]:
str[0:2:]

'He'

In [140]:
str[0::2]

'HloWloeyual'

In [141]:
str[::-1]

'lla uoy emocleW olleH'

In [142]:
"Hello" in str

True

In [143]:
"cse" in str

False

In [144]:
for i in range(1,11):
    print(i,end=" ")

1 2 3 4 5 6 7 8 9 10 

In [145]:
for i in range(1,11,2):
    print(i,end=" ")

1 3 5 7 9 

In [146]:
for i in range(2,11,2):
    print(i,end=" ")

2 4 6 8 10 

In [147]:
for i in range(5,101,5):
    print(i,end=" ")

5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95 100 

In [148]:
l=[12,15,39.50,'hello',[12,39,25,[34,'welcome',55],'cse']]
l

[12, 15, 39.5, 'hello', [12, 39, 25, [34, 'welcome', 55], 'cse']]

In [149]:
l[0]

12

In [150]:
l[3]

'hello'

In [151]:
l[4],l[4][3]

([12, 39, 25, [34, 'welcome', 55], 'cse'], [34, 'welcome', 55])

In [152]:
l[4][3][1]

'welcome'

In [153]:
l[4][3][1][:3]

'wel'

In [154]:
l[4][4]

'cse'

In [155]:
str+=" cse"

In [156]:
str.replace('Welcome','Cse')

'Hello Cse you all cse'

In [157]:
l[4][3][1]="cse"

In [158]:
l

[12, 15, 39.5, 'hello', [12, 39, 25, [34, 'cse', 55], 'cse']]

In [159]:
l.append("welcome")

In [160]:
l

[12, 15, 39.5, 'hello', [12, 39, 25, [34, 'cse', 55], 'cse'], 'welcome']

In [161]:
l.remove("Welcome")
l

ValueError: list.remove(x): x not in list

In [ ]:
l.insert(4,"Welcome")
l

In [ ]:
l.pop()
l

In [ ]:
l[2]

In [ ]:
print(39.54-39)

In [ ]:
l.remove(39.5)

In [ ]:
l.append("hello")

In [ ]:
l.insert(2,0.54)

In [ ]:
l

In [ ]:
str

In [ ]:
str.split(' ')

In [ ]:
dict={"Name":"Kris","Address":"Chennai","Mob No":9360050262}
print(dict)

In [ ]:
set={0,0,9}

In [ ]:
set

In [ ]:
dict["Name"]

In [ ]:
dict["Mob No"]

In [ ]:
len(dict)

In [ ]:
d1=dict.copy(),
d2=dict

In [ ]:
d1,d2

In [ ]:
dict.values()

In [ ]:
dict.keys()

In [ ]:
i=0
while(i<11):
    print("Welcome",end=" ")
    i+=1

In [ ]:
s="Welcome"
s

In [ ]:
def toprint():
    print(s)
    return
toprint()

In [ ]:
def toprint(str):
    print(str)
    return
toprint(s)

In [ ]:
a=12
def toprint(s):
    print(s*a,end=" ")
    return
toprint(s)

In [ ]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])

In [ ]:
a

In [ ]:
print(a)

In [ ]:
a.ndim

In [ ]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
b

In [ ]:
print(b)

In [ ]:
b.ndim

In [ ]:
c=np.arange(10,30)

In [ ]:
c

In [ ]:
d=np.arange(10,30,2)

In [ ]:
print(d)

In [ ]:
d.shape=(2,5)

In [ ]:
d

In [ ]:
d.ndim

In [ ]:
x=np.zeros(10)
x

In [ ]:
y=np.ones(10)
y

In [ ]:
z=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
z

In [ ]:
z.ndim

In [ ]:
z[0]

In [ ]:
z[1]

In [ ]:
z[0:1]

In [ ]:
z[2][2]

In [ ]:
z[:,1]

In [ ]:
z[:,2]

In [ ]:
z[:,2:4]

In [ ]:
z[1:3,0:3]

In [ ]:
z[0:2,0:2]

In [ ]:
z[2:4,2:4]

In [ ]:
o=np.array([[1,2,3],[4,5,6]])

In [163]:
o.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [164]:
o[1]

array([4, 5, 6])

In [166]:
o[:,1]

array([2, 5])

In [168]:
g+o

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [170]:
np.add(o,g)

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [172]:
np.subtract(o,g)

array([[0, 0, 0],
       [0, 0, 0]])

In [173]:
print(o-g)

[[0 0 0]
 [0 0 0]]


In [174]:
print(o*g)

[[ 1  4  9]
 [16 25 36]]


In [175]:
np.multiply(o,g)

array([[ 1,  4,  9],
       [16, 25, 36]])

In [176]:
print(o//g)

[[1 1 1]
 [1 1 1]]


In [177]:
np.sqrt(o)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])